### ISSUE TITLE
Error creating Security Group: InvalidGroup.Duplicate

### ISSUE THREAD

**Issue by stevepereira** [terraform-community-modules/tf_aws_bastion_s3_keys#19]
* aws_security_group.bastion: Error creating Security Group: InvalidGroup.Duplicate: The security group 'bastion.mydomain.com' already exists for VPC 'vpc-foo'

I've tried deleting it and reran but that doesn't help. I see it described in my state file as i'd expect after a run but it seems terraform is trying to add it even though it knows it's there...

Any ideas?

**Comment by antonbabenko** [comment]
If you see it in your state file, but resource does not exist when you look at AWS console, then you should run `terraform refresh` to refresh the state file. Does `terraform plan` show that it is going to add same resource one more time?

**Comment by stevepereira** [comment]
I see two in terraform plan:
+ aws_security_group.bastion
    description:                          "Bastion security group (only SSH inbound access is allowed)"
...
+ module.bastion.aws_security_group.bastion
    description:                          "Bastion security group (only SSH inbound access is allowed)"
...

With Identical config :\

**Comment by antonbabenko** [comment]
I don't think you should have two. Are you sure that you are not creating security group outside of module in other Terraform template?

**Comment by stevepereira** [comment]
I think I got it! I was inadvertently following two paths (autoscaling and dedicated instance) so I duplicated without realizing - thanks for the response!
