### ISSUE TITLE
public_ip is not exported by the module

### ISSUE THREAD

**Issue by bdirito** [terraform-community-modules/tf_aws_bastion_s3_keys#34]
According to the documentation:

```
After you run terraform apply you should be able to login to your bastion host like:

$ ssh ${module.bastion.ssh_user}@${module.bastion.instance_ip}
````

However module.bastion.instance_ip is not actually exported by the module. Furthermore it does not look like autoscaling groups have a way to list the ips of the machines involved. 
https://github.com/terraform-providers/terraform-provider-aws/issues/511

Thus at the minimum the documentation should be updated.

**Comment by antonbabenko** [comment]
Thanks for the finding, and yes, this module requires some attention.

I have just removed this command because it was there from the times when bastion host was not inside ASG.

**Comment by RobRoseKnows** [comment]
Is it possible to export the IP again? I'm trying to use this module to connect to a provisioner, it would be helpful if there was an easy way to get the IP/host so it could be passed into the `bastion_host` attribute of connection.
