### ISSUE TITLE
Support for Terraform 0.12

### ISSUE THREAD

**Issue by eliasdorneles** [terraform-community-modules/tf_aws_bastion_s3_keys#55]
Hello!

I tried using this module with Terraform 0.12 and I got errors due to the syntax change:

```
Error: Unsupported block type

  on .terraform/modules/bastion/main.tf line 6, in resource "aws_security_group" "bastion":
   6:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.


Error: Unsupported block type

  on .terraform/modules/bastion/main.tf line 51, in data "template_file" "user_data":
  51:   vars {

Blocks of type "vars" are not expected here. Did you mean to define argument
"vars"? If so, use the equals sign to assign it a value.
```

Apparently it's just a matter of adding the `=` sign ? (sorry, terraform noob here)

**Comment by eliasdorneles** [comment]
I've made a PR for this here: https://github.com/terraform-community-modules/tf_aws_bastion_s3_keys/pull/56

For others needing 0.12 support *right now*, you can use the branch from the PR:

      source        = "github.com/eliasdorneles/tf_aws_bastion_s3_keys?ref=tf-012-support"

**Comment by CarpathianUA** [comment]
+1

**Comment by antonbabenko** [comment]
[v2.0.0](https://github.com/terraform-community-modules/tf_aws_bastion_s3_keys/releases/v2.0.0) of this module is Terraform 0.12 ready.

Thanks to @eliasdorneles and others who was involved on #56
