### ISSUE TITLE
Why autoscaling groups?

### ISSUE THREAD

**Issue by RobRoseKnows** [terraform-community-modules/tf_aws_bastion_s3_keys#58]
I'm curious as to why this module moved away from just making an AWS Instance and instead using an autoscaling group. I'd like to create a bastion that I can use as a jump box during the provisioning of certain private instances in private subnets as well as to SSH into those boxes after provisioning. I should be able to do that with just an `aws_instance` no? Is this meant for some other usage? Why create an autoscaling group with only one instance?

**Comment by max-rocket-internet** [comment]
Because any instance that exists outside of an autoscaling group is not resilient.

Instances that belong to an ASG are monitored and replaced automatically if: they crash, are terminated by AWS or fail healthcheck.

**Comment by antonbabenko** [comment]
@RobRoseKnows Also, check this out - https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-maintain-instance-levels.html

Closing this one.
