### ISSUE TITLE
Question: Equivalent of elastic ip tricks but for ipv6 ?

### ISSUE THREAD

**Issue by allan-simon** [terraform-community-modules/tf_aws_bastion_s3_keys#65]
I would like to be good net citizen and use a IPv6 for the bastion 

is there a way to have this, so that I can associate the IPv6 to the dynamically created bastion instance, in order to then use this IPv6 to create a AAAA record  `bastion.example.com`  ? 

(I've read that elastic ip is not supported for ipv6)

**Comment by antonbabenko** [comment]
HI Allan,

I think you are right that it is not possible to use Elastic IPv6 and thus you can't make bastion to have IPv6.

If you really want to get IPv6 to work for your bastion, you can use [Network Load Balancer](https://aws.amazon.com/about-aws/whats-new/2020/11/network-load-balancer-supports-ipv6) in front of your bastion host though it will be more expensive and increase complexity.
