### ISSUE TITLE
Permission denied on public key.

### ISSUE THREAD

**Issue by ffrizzo** [terraform-community-modules/tf_aws_bastion_s3_keys#8]
I created a new bucket on s3 and add my public keys on this bucket. 
But I'm getting a "Permission denied (publickey)".

My Module configuration
```
module "bastion" {
  source                = "github.com/terraform-community-modules/tf_aws_bastion_s3_keys"
  name                  = "foodlogiqBastion"
  instance_type         = "${var.instance_type}"
  ami                   = "${module.bastion_ami.ami_id}"
  region                = "${var.region}"
  iam_instance_profile  = "${aws_iam_instance_profile.s3_readonly.name}"
  s3_bucket_name        = "public-keys-bastion"
  vpc_id                = "${module.vpc.vpc_id}"
  subnet_ids            = ["${module.vpc.public_subnets}"]
  keys_update_frequency = "30 * * * *"
}

resource "aws_iam_instance_profile" "s3_readonly" {
  name  = "s3-readonly"
  roles = ["${aws_iam_role.s3_readonly.name}"]
}

resource "aws_iam_role" "s3_readonly" {
  name               = "s3-readonly-role"
  path               = "/"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "s3_readonly_policy" {
  name   = "s3-readonly-policy"
  role   = "${aws_iam_role.s3_readonly.id}"
  policy = <<EOF
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1425916919000",
            "Effect": "Allow",
            "Action": [
                "s3:List*",
                "s3:Get*"
            ],
            "Resource": "*"
        }
    ]
}
EOF
}
```

**Comment by antonbabenko** [comment]
Should work.

Check "EC2->Instance Settings->Get System Log" for the bastion instance. It often contains helpful output.

Can you verify that public keys are readable by the provided role (using [policy simulator](https://policysim.aws.amazon.com/home/index.jsp?#roles/s3-readonly-role), for example)?

Check syslog on the machine itself to verify output of shell script it runs. Are you sure that crontab expression is set correctly (now it says - once an hour on 30 min)?

**Comment by ffrizzo** [comment]
@antonbabenko Thanks for reply so fast.

Yes I used policy simulator and this here is the result
![screen shot 2016-10-26 at 10 16 19](https://cloud.githubusercontent.com/assets/179184/19725611/44dc1536-9b65-11e6-9b7d-a034aabb5e0f.png)

Yes the cron expression is correct. 

I'll close this issue because this work now(like magic). I just destroyed everything and create again.
